# Libraries

In [3]:
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import sklearn.preprocessing
import sklearn.cross_validation

/home/ggomarr/.local/lib/python3.5/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


# Read data

In [4]:
work_dir='/home/ggomarr/Documents/Education/20170623 Udemy - Machine Learning A-Z: Hands-On Python and R in Data Science/' + \
         'Course data/Part 1 - Data Preprocessing/Section 2 - Data preprocessing/'

In [5]:
df=pd.read_csv(work_dir+'Data.csv')
df.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [4]:
X=df.iloc[:,:-1].values
Y=df.iloc[:,-1].values
X,Y

(array([['France', 44.0, 72000.0],
        ['Spain', 27.0, 48000.0],
        ['Germany', 30.0, 54000.0],
        ['Spain', 38.0, 61000.0],
        ['Germany', 40.0, nan],
        ['France', 35.0, 58000.0],
        ['Spain', nan, 52000.0],
        ['France', 48.0, 79000.0],
        ['Germany', 50.0, 83000.0],
        ['France', 37.0, 67000.0]], dtype=object),
 array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'], dtype=object))

# Clean up missing data

In [7]:
imputer=sklearn.preprocessing.Imputer(missing_values='NaN',strategy='mean',axis=0).fit(X[:,1:3])
X[:,1:3]=imputer.transform(X[:,1:3])
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

# Create dummy variables

In [14]:
label_encoder=sklearn.preprocessing.LabelEncoder().fit(X[:,0])
X[:,0]=label_encoder.transform(X[:,0])
one_hot_encoder=sklearn.preprocessing.OneHotEncoder(categorical_features=[0]).fit(X)
X=one_hot_encoder.transform(X).toarray()
X

array([[  1.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          4.40000000e+01,   7.20000000e+04],
       [  0.00000000e+00,   0.00000000e+00,   1.00000000e+00,
          2.70000000e+01,   4.80000000e+04],
       [  0.00000000e+00,   1.00000000e+00,   0.00000000e+00,
          3.00000000e+01,   5.40000000e+04],
       [  0.00000000e+00,   0.00000000e+00,   1.00000000e+00,
          3.80000000e+01,   6.10000000e+04],
       [  0.00000000e+00,   1.00000000e+00,   0.00000000e+00,
          4.00000000e+01,   6.37777778e+04],
       [  1.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          3.50000000e+01,   5.80000000e+04],
       [  0.00000000e+00,   0.00000000e+00,   1.00000000e+00,
          3.87777778e+01,   5.20000000e+04],
       [  1.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          4.80000000e+01,   7.90000000e+04],
       [  0.00000000e+00,   1.00000000e+00,   0.00000000e+00,
          5.00000000e+01,   8.30000000e+04],
       [  1.00000000e+00,   0.0000000

# Create categorical labels

In [15]:
label_encoder=sklearn.preprocessing.LabelEncoder().fit(Y)
Y=label_encoder.transform(Y)
Y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

# Feature scaling

In [21]:
standard_scaler=sklearn.preprocessing.StandardScaler().fit(X)
X=standard_scaler.transform(X)
X

array([[  1.22474487e+00,  -6.54653671e-01,  -6.54653671e-01,
          7.58874362e-01,   7.49473254e-01],
       [ -8.16496581e-01,  -6.54653671e-01,   1.52752523e+00,
         -1.71150388e+00,  -1.43817841e+00],
       [ -8.16496581e-01,   1.52752523e+00,  -6.54653671e-01,
         -1.27555478e+00,  -8.91265492e-01],
       [ -8.16496581e-01,  -6.54653671e-01,   1.52752523e+00,
         -1.13023841e-01,  -2.53200424e-01],
       [ -8.16496581e-01,   1.52752523e+00,  -6.54653671e-01,
          1.77608893e-01,   6.63219199e-16],
       [  1.22474487e+00,  -6.54653671e-01,  -6.54653671e-01,
         -5.48972942e-01,  -5.26656882e-01],
       [ -8.16496581e-01,  -6.54653671e-01,   1.52752523e+00,
          0.00000000e+00,  -1.07356980e+00],
       [  1.22474487e+00,  -6.54653671e-01,  -6.54653671e-01,
          1.34013983e+00,   1.38753832e+00],
       [ -8.16496581e-01,   1.52752523e+00,  -6.54653671e-01,
          1.63077256e+00,   1.75214693e+00],
       [  1.22474487e+00,  -6.5465367

# Train/test split

In [22]:
X_train,X_test,Y_train,Y_test=sklearn.cross_validation.train_test_split(X,Y,test_size=0.2,random_state=0)

In [23]:
X_train,Y_train

(array([[ -8.16496581e-01,   1.52752523e+00,  -6.54653671e-01,
           1.77608893e-01,   6.63219199e-16],
        [  1.22474487e+00,  -6.54653671e-01,  -6.54653671e-01,
          -2.58340208e-01,   2.93712492e-01],
        [ -8.16496581e-01,  -6.54653671e-01,   1.52752523e+00,
          -1.71150388e+00,  -1.43817841e+00],
        [ -8.16496581e-01,  -6.54653671e-01,   1.52752523e+00,
           0.00000000e+00,  -1.07356980e+00],
        [  1.22474487e+00,  -6.54653671e-01,  -6.54653671e-01,
           1.34013983e+00,   1.38753832e+00],
        [ -8.16496581e-01,  -6.54653671e-01,   1.52752523e+00,
          -1.13023841e-01,  -2.53200424e-01],
        [  1.22474487e+00,  -6.54653671e-01,  -6.54653671e-01,
           7.58874362e-01,   7.49473254e-01],
        [  1.22474487e+00,  -6.54653671e-01,  -6.54653671e-01,
          -5.48972942e-01,  -5.26656882e-01]]),
 array([1, 1, 1, 0, 1, 0, 0, 1]))

In [24]:
X_test,Y_test

(array([[-0.81649658,  1.52752523, -0.65465367, -1.27555478, -0.89126549],
        [-0.81649658,  1.52752523, -0.65465367,  1.63077256,  1.75214693]]),
 array([0, 0]))