# Libraries

In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import sklearn.preprocessing
import sklearn.cross_validation
import sklearn.linear_model
import statsmodels.formula.api as sm

/home/ggomarr/.local/lib/python3.5/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


# Read data

In [2]:
work_dir='/home/ggomarr/Documents/Education/20170623 Udemy - Machine Learning A-Z: Hands-On Python and R in Data Science/' + \
             'Course data/Part 2 - Regression/Section 5 - Multiple Linear Regression/'

In [3]:
df=pd.read_csv(work_dir+'50_Startups.csv')
df.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [4]:
X=df.iloc[:,:-1].values
Y=df.iloc[:,-1].values
X,Y

(array([[165349.2, 136897.8, 471784.1, 'New York'],
        [162597.7, 151377.59, 443898.53, 'California'],
        [153441.51, 101145.55, 407934.54, 'Florida'],
        [144372.41, 118671.85, 383199.62, 'New York'],
        [142107.34, 91391.77, 366168.42, 'Florida'],
        [131876.9, 99814.71, 362861.36, 'New York'],
        [134615.46, 147198.87, 127716.82, 'California'],
        [130298.13, 145530.06, 323876.68, 'Florida'],
        [120542.52, 148718.95, 311613.29, 'New York'],
        [123334.88, 108679.17, 304981.62, 'California'],
        [101913.08, 110594.11, 229160.95, 'Florida'],
        [100671.96, 91790.61, 249744.55, 'California'],
        [93863.75, 127320.38, 249839.44, 'Florida'],
        [91992.39, 135495.07, 252664.93, 'California'],
        [119943.24, 156547.42, 256512.92, 'Florida'],
        [114523.61, 122616.84, 261776.23, 'New York'],
        [78013.11, 121597.55, 264346.06, 'California'],
        [94657.16, 145077.58, 282574.31, 'New York'],
        [91749.1

# Clean up missing data

In [11]:
sum(np.isnan(X)),sum(np.isnan(Y))

(array([0, 0, 0, 0, 0]), 0)

In [9]:
# imputer=sklearn.preprocessing.Imputer(missing_values='NaN',strategy='mean',axis=0).fit(X[:,1:3])
# X[:,1:3]=imputer.transform(X[:,1:3])
# X

# Create dummy variables

In [5]:
label_encoder=sklearn.preprocessing.LabelEncoder().fit(X[:,3])
X[:,3]=label_encoder.transform(X[:,3])
one_hot_encoder=sklearn.preprocessing.OneHotEncoder(categorical_features=[3]).fit(X)
X=one_hot_encoder.transform(X).toarray()
X

array([[  0.00000000e+00,   0.00000000e+00,   1.00000000e+00,
          1.65349200e+05,   1.36897800e+05,   4.71784100e+05],
       [  1.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          1.62597700e+05,   1.51377590e+05,   4.43898530e+05],
       [  0.00000000e+00,   1.00000000e+00,   0.00000000e+00,
          1.53441510e+05,   1.01145550e+05,   4.07934540e+05],
       [  0.00000000e+00,   0.00000000e+00,   1.00000000e+00,
          1.44372410e+05,   1.18671850e+05,   3.83199620e+05],
       [  0.00000000e+00,   1.00000000e+00,   0.00000000e+00,
          1.42107340e+05,   9.13917700e+04,   3.66168420e+05],
       [  0.00000000e+00,   0.00000000e+00,   1.00000000e+00,
          1.31876900e+05,   9.98147100e+04,   3.62861360e+05],
       [  1.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          1.34615460e+05,   1.47198870e+05,   1.27716820e+05],
       [  0.00000000e+00,   1.00000000e+00,   0.00000000e+00,
          1.30298130e+05,   1.45530060e+05,   3.23876680e+05],


# Avoid the dummy variable trap

In [6]:
X=X=np.delete(X,0,1)
X

array([[  0.00000000e+00,   1.00000000e+00,   1.65349200e+05,
          1.36897800e+05,   4.71784100e+05],
       [  0.00000000e+00,   0.00000000e+00,   1.62597700e+05,
          1.51377590e+05,   4.43898530e+05],
       [  1.00000000e+00,   0.00000000e+00,   1.53441510e+05,
          1.01145550e+05,   4.07934540e+05],
       [  0.00000000e+00,   1.00000000e+00,   1.44372410e+05,
          1.18671850e+05,   3.83199620e+05],
       [  1.00000000e+00,   0.00000000e+00,   1.42107340e+05,
          9.13917700e+04,   3.66168420e+05],
       [  0.00000000e+00,   1.00000000e+00,   1.31876900e+05,
          9.98147100e+04,   3.62861360e+05],
       [  0.00000000e+00,   0.00000000e+00,   1.34615460e+05,
          1.47198870e+05,   1.27716820e+05],
       [  1.00000000e+00,   0.00000000e+00,   1.30298130e+05,
          1.45530060e+05,   3.23876680e+05],
       [  0.00000000e+00,   1.00000000e+00,   1.20542520e+05,
          1.48718950e+05,   3.11613290e+05],
       [  0.00000000e+00,   0.0000000

# Create categorical labels

In [11]:
# label_encoder=sklearn.preprocessing.LabelEncoder().fit(Y)
# Y=label_encoder.transform(Y)
# Y

# Feature scaling

In [14]:
# standard_scaler=sklearn.preprocessing.StandardScaler().fit(X)
# X=standard_scaler.transform(X)
# X

# Train/test split

In [7]:
X_train,X_test,Y_train,Y_test=sklearn.cross_validation.train_test_split(X,Y,test_size=0.2,random_state=0)
Y_train.size,Y_test.size

(40, 10)

In [67]:
X_train,Y_train

(array([[  1.00000000e+00,   0.00000000e+00,   5.54939500e+04,
           1.03057490e+05,   2.14634810e+05],
        [  0.00000000e+00,   1.00000000e+00,   4.60140200e+04,
           8.50474400e+04,   2.05517640e+05],
        [  1.00000000e+00,   0.00000000e+00,   7.53288700e+04,
           1.44135980e+05,   1.34050070e+05],
        [  0.00000000e+00,   0.00000000e+00,   4.64260700e+04,
           1.57693920e+05,   2.10797670e+05],
        [  1.00000000e+00,   0.00000000e+00,   9.17491600e+04,
           1.14175790e+05,   2.94919570e+05],
        [  1.00000000e+00,   0.00000000e+00,   1.30298130e+05,
           1.45530060e+05,   3.23876680e+05],
        [  1.00000000e+00,   0.00000000e+00,   1.19943240e+05,
           1.56547420e+05,   2.56512920e+05],
        [  0.00000000e+00,   1.00000000e+00,   1.00023000e+03,
           1.24153040e+05,   1.90393000e+03],
        [  0.00000000e+00,   1.00000000e+00,   5.42050000e+02,
           5.17431500e+04,   0.00000000e+00],
        [  0.000000

In [68]:
X_test,Y_test

(array([[  1.00000000e+00,   0.00000000e+00,   6.60515200e+04,
           1.82645560e+05,   1.18148200e+05],
        [  0.00000000e+00,   0.00000000e+00,   1.00671960e+05,
           9.17906100e+04,   2.49744550e+05],
        [  1.00000000e+00,   0.00000000e+00,   1.01913080e+05,
           1.10594110e+05,   2.29160950e+05],
        [  1.00000000e+00,   0.00000000e+00,   2.78929200e+04,
           8.47107700e+04,   1.64470710e+05],
        [  1.00000000e+00,   0.00000000e+00,   1.53441510e+05,
           1.01145550e+05,   4.07934540e+05],
        [  0.00000000e+00,   1.00000000e+00,   7.21076000e+04,
           1.27864550e+05,   3.53183810e+05],
        [  0.00000000e+00,   1.00000000e+00,   2.02295900e+04,
           6.59479300e+04,   1.85265100e+05],
        [  0.00000000e+00,   1.00000000e+00,   6.11363800e+04,
           1.52701920e+05,   8.82182300e+04],
        [  1.00000000e+00,   0.00000000e+00,   7.39945600e+04,
           1.22782750e+05,   3.03319260e+05],
        [  1.000000

# Regression using sklearn.linear_model.LinearRegression()

In [69]:
mult_reg=sklearn.linear_model.LinearRegression().fit(X_train,Y_train)
mult_reg.score(X_train,Y_train),mult_reg.score(X_test,Y_test)

(0.9501847627493607, 0.93470684732829856)

# Feature selection using statsmodels.formula.api.OLS

## Adding an explicit 'intercept feature'

In [8]:
X_train_ext=np.append(np.ones((X_train.shape[0],1)),X_train,1)
X_test_ext=np.append(np.ones((X_test.shape[0],1)),X_test,1)

## Backward elimination

In [9]:
p_limit=0.05
be_feat=list(range(X_train_ext.shape[1]))
done=False
while not done:
    be_mult_reg_OLS=sm.OLS(Y_train,X_train_ext[:,be_feat]).fit()
    p_max=max(be_mult_reg_OLS.pvalues)
    if p_max>p_limit:
        p_max_pos=np.argmax(be_mult_reg_OLS.pvalues)
        print('Removing feature {} with p {:.3f}'.format(be_feat[p_max_pos],p_max))
        be_feat=be_feat[:p_max_pos]+be_feat[p_max_pos+1:]
    else:
        done=True
be_mult_reg_OLS.summary()

Removing feature 2 with p 0.850
Removing feature 1 with p 0.729
Removing feature 4 with p 0.650
Removing feature 5 with p 0.071


<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.945
Model:                            OLS   Adj. R-squared:                  0.944
Method:                 Least Squares   F-statistic:                     652.4
Date:                Wed, 05 Jul 2017   Prob (F-statistic):           1.56e-25
Time:                        10:58:55   Log-Likelihood:                -423.09
No. Observations:                  40   AIC:                             850.2
Df Residuals:                      38   BIC:                             853.6
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       4.842e+04   2842.717     17.032      0.000    4.27e+04    5.42e+04
x1             0.8516      0.033     25.542      0.000       0.784       0.919
==============================================================================
Omnibus:                       13.132   Durbin-Watson:                   2.325
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               16.254
Skew:                          -0.991   Prob(JB):                     0.000295
Kurtosis:                       5.413   Cond. No.                     1.57e+05
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.57e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

## Forward selection

In [11]:
p_limit=0.05
fs_feat=[]
candidates=list(range(X_train_ext.shape[1]))
done=False
while not done and len(candidates)>0:
    aux_OLS_lst=[sm.OLS(Y_train,X_train_ext[:,fs_feat+[candidate]]).fit() for candidate in candidates]
    p_vals=[aux_OLS.pvalues[-1] for aux_OLS in aux_OLS_lst]
    p_min=min(p_vals)
    if p_min<p_limit:
        p_min_pos=np.argmin(p_vals)
        print('Adding feature {} with p {:.3f}'.format(candidates[p_min_pos],p_min))
        fs_feat.append(candidates[p_min_pos])
        candidates=candidates[:p_min_pos]+candidates[p_min_pos+1:]
        fs_mult_reg_OLS=aux_OLS_lst[p_min_pos]
    else:
        done=True
fs_mult_reg_OLS.summary()

Adding feature 3 with p 0.000
Adding feature 0 with p 0.000


<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.945
Model:                            OLS   Adj. R-squared:                  0.944
Method:                 Least Squares   F-statistic:                     652.4
Date:                Wed, 05 Jul 2017   Prob (F-statistic):           1.56e-25
Time:                        11:00:23   Log-Likelihood:                -423.09
No. Observations:                  40   AIC:                             850.2
Df Residuals:                      38   BIC:                             853.6
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1             0.8516      0.033     25.542      0.000       0.784       0.919
const       4.842e+04   2842.717     17.032      0.000    4.27e+04    5.42e+04
==============================================================================
Omnibus:                       13.132   Durbin-Watson:                   2.325
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               16.254
Skew:                          -0.991   Prob(JB):                     0.000295
Kurtosis:                       5.413   Cond. No.                     1.57e+05
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.57e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

## Checking against the all in sklearn models

In [110]:
mult_reg.score(X_train,Y_train),mult_reg.score(X_test,Y_test)

(0.9501847627493607, 0.93470684732829856)

In [111]:
be_mult_reg=sklearn.linear_model.LinearRegression().fit(X_train_ext[:,be_feat],Y_train)
be_mult_reg.score(X_train_ext[:,be_feat],Y_train),be_mult_reg.score(X_test_ext[:,be_feat],Y_test)

(0.94495897783630445, 0.94645876077872193)

In [112]:
fs_mult_reg=sklearn.linear_model.LinearRegression().fit(X_train_ext[:,fs_feat],Y_train)
fs_mult_reg.score(X_train_ext[:,fs_feat],Y_train),be_mult_reg.score(X_test_ext[:,fs_feat],Y_test)

(0.94495897783630445, 0.94645876077872193)